# Generated by Django 5.1.2 on 2024-11-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_forum_email_remove_forum_name_forum_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='user',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='link',
        ),
    ]
